sudo: false
language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

env:
  global:
    - LD_LIBRARY_PATH=/usr/local/lib

addons:
  apt:
    packages:
    - libgtk-3-dev

install:

before_script:
  - rustup component add rustfmt

  - WD="$PWD"
  - cd "$HOME"
  - curl -LO "https://github.com/gkoz/gtk-bootstrap/releases/download/gtk-3.18.1-2/deps.txz"
  - tar xf deps.txz
  - cd "$WD"
  - export PKG_CONFIG_PATH="$HOME/local/lib/pkgconfig"
  - export LD_LIBRARY_PATH="$HOME/local/lib/"

script:
  - cargo fmt -- --check
  - cargo build
  - cargo test
