language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
sudo: false
env:
  global:
    - LD_LIBRARY_PATH=/usr/local/lib
addons:
  apt:
    packages:
    - libgtk-3-dev
