language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
sudo: false
env:
  global:
    - LD_LIBRARY_PATH=/usr/local/lib
addons:
  apt:
    sources:
    - debian-sid
    packages:
    - libgtk-3-dev
#    - shellcheck

install:

before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - which rustfmt || cargo install rustfmt

  - WD="$PWD"
  - cd "$HOME"
  - curl -LO "https://github.com/gkoz/gtk-bootstrap/releases/download/gtk-3.18.1-2/deps.txz"
  - tar xf deps.txz
  - cd "$WD"
  - export PKG_CONFIG_PATH="$HOME/local/lib/pkgconfig"
  - export LD_LIBRARY_PATH="$HOME/local/lib/"

script:
  - cargo fmt -- --write-mode=diff
  - cargo build
  - cargo test
  - shellcheck install
